# pv-pvc.yaml
# Test namespace için
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/test-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-mysql-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-wordpress-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/test-wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-wordpress-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Production namespace için
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prod-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-mysql-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-wordpress-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prod-wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-wordpress-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi