# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: test
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64: rootpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64: rootpassword